// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVt5RhajHs-31fF8nwi8vBz0RLAbK5e6I',
    appId: '1:308736762863:web:bc3c1d03992edf65e30c1a',
    messagingSenderId: '308736762863',
    projectId: 'plantify-bb8fb',
    authDomain: 'plantify-bb8fb.firebaseapp.com',
    storageBucket: 'plantify-bb8fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1uPrOXwrb43f3yJ5K3wBgQWXkfschUs8',
    appId: '1:308736762863:android:811702e54130e1ace30c1a',
    messagingSenderId: '308736762863',
    projectId: 'plantify-bb8fb',
    storageBucket: 'plantify-bb8fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcA_8wpbozgPQWBvikAyC57qnrVu_MyFg',
    appId: '1:308736762863:ios:425f22e233f52c71e30c1a',
    messagingSenderId: '308736762863',
    projectId: 'plantify-bb8fb',
    storageBucket: 'plantify-bb8fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVt5RhajHs-31fF8nwi8vBz0RLAbK5e6I',
    appId: '1:308736762863:web:adaeea895875ea4ee30c1a',
    messagingSenderId: '308736762863',
    projectId: 'plantify-bb8fb',
    authDomain: 'plantify-bb8fb.firebaseapp.com',
    storageBucket: 'plantify-bb8fb.appspot.com',
  );
}
